---
- name: "Build container with ansible"
  hosts: localhost
  tasks:
  - name: stop running container
    command: docker stop mveyone/docker-comose-nodejs-app
    ignore_errors: yes

  - name: remove stopped container
    command: docker rm mveyone/docker-comose-nodejs-app
    ignore_errors: yes
  
  - name: remove used image
    command: docker rmi $JOB_NAME:v1.$(BUILD_ID-1)
    
  - name: build docker image from dockerfile
    command: docker build -t $JOB_NAME:v1.$BUILD_ID .

  - name: create tag to image
    command: docker tag $JOB_NAME:v1.$BUILD_ID mveyone/ejs-node-mongo-express-app:2.0

  - name: push image to dockerhub
    command: docker push mveyone/docker-comose-nodejs-app

  # - name: run container from image
  #   command: docker run -d --name my-app -p 3000 mveyone/ejs-node-mongo-express-app:2.0